version: "3.9"

services:
  app:
    image: freazerkrd/english_exercises
    build:
      context: .

    restart: always
    volumes:
      - ./app:/app
    environment:
      - BOT_TOKEN=${BOT_TOKEN}