version: "3.9"

services:
  app:
    image: freazerkrd/english_exercises
    build:
      context: .
      args:
        - DEV=${DEV}

    restart: always
    volumes:
      - .:/app
    environment:
      - BOT_TOKEN=${BOT_TOKEN}